export const CREATE_MESSAGE = 'CREATE_MESSAGE'


export const FOLLOW = 'FOLLOW'
export const UNFOLLOW = 'UNFOLLOW'

export const TOGGLE_IS_FOLLOWING = 'TOGGLE_IS_FOLLOWING'
export const SET_USERS = 'SET_USERS'
export const TOGGLE_IS_FETCHING_USERS = 'TOGGLE_IS_FETCHING_USERS'

export const SET_ACTIVE_PAGE = 'SET_ACTIVE_PAGE'
export const SET_TOTAL_COUNT = 'SET_TOTAL_COUNT'


