export const ADD_POST = 'ADD_POST'
export const UPDATE_POST_TEXT = 'UPDATE_POST_TEXT'
export const UPDATE_MESSAGE_TEXT = 'UPDATE_MESSAGE_TEXT'
export const CREATE_MESSAGE = 'CREATE_MESSAGE'


export const FOLLOW = 'FOLLOW'
export const UNFOLLOW = 'UNFOLLOW'

export const TOGGLE_IS_FOLLOWING = 'TOGGLE_IS_FOLLOWING'
export const SET_USERS = 'SET_USERS'
export const TOGGLE_IS_FETCHING_USERS = 'TOGGLE_IS_FETCHING_USERS'

export const SET_ACTIVE_PAGE = 'SET_ACTIVE_PAGE'
export const SET_TOTAL_COUNT = 'SET_TOTAL_COUNT'

export const SET_USER_PROFILE = 'SET_USER_PROFILE'
export const SET_USER_DATA = 'SET_USER_DATA'
export const GET_STATUS = 'GET_STATUS'

