export const ADD_POST = 'ADD_POST'
export const UPDATE_POST_TEXT = 'UPDATE_POST_TEXT'
export const UPDATE_MESSAGE_TEXT = 'UPDATE_MESSAGE_TEXT'
export const CREATE_MESSAGE = 'CREATE_MESSAGE'


export const FOLLOW_UNFOLLOW = 'FOLLOW_UNFOLLOW'
export const SET_USERS = 'SET_USERS'

